Estoque.Presentation/Models/Solicitacao.cs
namespace Estoque.Presentation.Models
{
    public class Solicitacao
    {
        public int IdSolicitacao { get; set; }
        public string NomeEquipamento { get; set; }
        public int QtdSolicitada { get; set; }
        public string NomeSolicitante { get; set; }
        public bool Concluida { get; set; }
    }
}

Estoque.Presentation/Controllers/MaquinaSolicitadaController.cs
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Estoque.Domain.Entities;
using Estoque.Infra.Repositories;

namespace Estoque.Presentation.Controllers
{
    public class MaquinaSolicitadaController : Controller
    {
        MaquinaSolicitadaRepository repository = new MaquinaSolicitadaRepository();
        public IActionResult Index()
        {
            try
            {
                return RedirectToAction("Index", "Solicitacao");
            }
            catch
            {
                ViewBag.Erro = "Ocorreu um Erro, contate o Administrador do Sistema!";

                return View();
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create([Bind("Id,QtdSolicitada,SolicitanteId,EquipamentoId,Concluida")] MaquinaSolicitada maquinaSolicitada, string nomeEquipamento, string nomeSolicitante)
        {
            try
            {
                HttpClient client = new HttpClient();

                SolicitanteRepository solicitanteRepository = new SolicitanteRepository();
                Solicitante solicitante = solicitanteRepository.ProcurarPorNome(nomeSolicitante);
                maquinaSolicitada.SolicitanteId = solicitante.Id;

                EquipamentoRepository equipamentoRepository = new EquipamentoRepository();
                Equipamento equipamento = equipamentoRepository.ProcurarPorNome(nomeEquipamento);
                maquinaSolicitada.EquipamentoId = equipamento.Id;

                if(maquinaSolicitada.Concluida == true)
                {
                    equipamento.QtdEstoque -= maquinaSolicitada.QtdSolicitada;

                    equipamentoRepository.Update(equipamento);
                }

                repository.Add(maquinaSolicitada);

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                ViewBag.Erro = "Ocorreu um Erro, contate o Administrador do Sistema!";

                return View();
            }
        }

        [HttpGet]
        public ActionResult Edit(int id, string nomeEquipamento, string nomeSolicitante)
        {
            MaquinaSolicitadaRepository repository = new MaquinaSolicitadaRepository();
            var maquinaSolicitada = repository.GetMaquinaSolicitada(id);

            EquipamentoRepository equipamentoRepository = new EquipamentoRepository();
            var equipamento = equipamentoRepository.GetById(maquinaSolicitada.EquipamentoId);
            nomeEquipamento = equipamento.Nome;

            SolicitanteRepository solicitanteRepository = new SolicitanteRepository();
            var solicitante = solicitanteRepository.GetById(maquinaSolicitada.SolicitanteId);
            nomeSolicitante = solicitante.Nome;

            if (maquinaSolicitada.Concluida == true)
            {
                equipamento.QtdEstoque -= maquinaSolicitada.QtdSolicitada;

                equipamentoRepository.Update(equipamento);
            }

            return View(maquinaSolicitada);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(int id, [Bind("Id,QtdSolicitada,SolicitanteId,EquipamentoId,Concluida")] MaquinaSolicitada maquinaSolicitada, string nomeEquipamento, string nomeSolicitante)
        {
            EquipamentoRepository equipamentoRepository = new EquipamentoRepository();
            Equipamento equipamento = equipamentoRepository.ProcurarPorNome(nomeEquipamento);
            maquinaSolicitada.EquipamentoId = equipamento.Id;

            SolicitanteRepository solicitanteRepository = new SolicitanteRepository();
            Solicitante solicitante = solicitanteRepository.ProcurarPorNome(nomeSolicitante);
            maquinaSolicitada.SolicitanteId = solicitante.Id;

            MaquinaSolicitadaRepository repository = new MaquinaSolicitadaRepository();
            repository.Update(maquinaSolicitada);

            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            MaquinaSolicitadaRepository repository = new MaquinaSolicitadaRepository();
            var maquinaSolicitada = repository.GetMaquinaSolicitada(id);

            return View(maquinaSolicitada);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            MaquinaSolicitadaRepository repository = new MaquinaSolicitadaRepository();
            var maquinaSolicitada = repository.GetMaquinaSolicitada(id);

            if(maquinaSolicitada != null)
            {
                repository.Delete(maquinaSolicitada);
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Estoque.Presentation/Controllers/SolicitacaoController.cs
using System.Text;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using Estoque.Domain.Entities;
using Estoque.Infra.Repositories;

namespace Estoque.Presentation.Controllers
{
    public class SolicitacaoController : Controller
    {
        SolicitacaoRepository repository = new SolicitacaoRepository();
        public IActionResult Index()
        {
            try
            {
                IEnumerable<Solicitacao> lista = (IEnumerable<Solicitacao>)repository.Get();
                lista = lista.OrderByDescending(t => t.IdSolicitacao);

                return View(lista);
            }
            catch (Exception ex)
            {
                ViewBag.Erro = "Ocorreu um Erro, contate o Administrador do Sistema!";

                return View();
            }
        }
    }
}

Estoque.Presentation/Views/Solicitacao/Index.cshtml
@model IEnumerable<Estoque.Domain.Entities.Solicitacao>

@{
    ViewData["Title"] = "Lista de Equipamentos";
}

@if (ViewBag.Erro != null)
{
    <h4>@ViewBag.Erro</h4>
}

<form>
    <h1>Lista de Equipamentos</h1>

    <p>
         <input type="submit" value="Cadastrar Novo" class="btn btn-success" asp-action="Create" asp-controller="MaquinaSolicitada"/>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>Id da Solicitação</th>
                <th>Nome do Equipamento</th>
                <th>Quantidade Solicitada</th>
                <th>Nome do Solicitante</th>
                <th>Concluída</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(modelItem => item.IdSolicitacao)</td>
                    <td>@Html.DisplayFor(modelItem => item.NomeEquipamento)</td>
                    <td>@Html.DisplayFor(modelItem => item.QtdSolicitada)</td>
                    <td>@Html.DisplayFor(modelItem => item.NomeSolicitante)</td>
                    <td>@Html.CheckBoxFor(modelItem => item.Concluida)</td>
                    <td>
                        <input type="submit" value="Editar Dados" class="btn btn-warning" asp-action="Edit" asp-controller="MaquinaSolicitada" asp-route-id="@item.IdSolicitacao"/> |
                        <input type="submit" value="Deletar Dados" class="btn btn-danger" asp-action="Delete" asp-controller="MaquinaSolicitada" asp-route-id="@item.IdSolicitacao"/>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</form>